# Generated by Django 5.1.1 on 2024-09-19 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_alter_card_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='bank_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='cvv',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card',
            name='card_type',
            field=models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'MasterCard')], max_length=255),
        ),
    ]
