# Generated by Django 5.1.1 on 2024-09-19 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_card_bank_name_card_cvv_alter_card_card_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
