# Generated by Django 5.1.1 on 2024-10-18 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_category_category_icon_category_is_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='planned_expenses',
        ),
    ]
