# Generated by Django 5.1.1 on 2024-09-17 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='categories',
        ),
    ]
