# Generated by Django 5.1.1 on 2024-09-19 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notification_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='send_at',
            field=models.DateTimeField(),
            preserve_default=False,
        ),
    ]
