# Generated by Django 5.1.1 on 2024-09-17 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='transfer',
            table='transfers',
        ),
    ]
