# Generated by Django 5.1.1 on 2024-10-26 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='goal_color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
        migrations.AddField(
            model_name='goal',
            name='goal_icon',
            field=models.CharField(default='default_icon', max_length=255),
        ),
    ]
