# Generated by Django 5.1.1 on 2024-11-13 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_goal_goal_color_goal_goal_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goal',
            options={'ordering': ['-priority']},
        ),
        migrations.RemoveField(
            model_name='goal',
            name='account',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='end_date',
        ),
        migrations.AlterField(
            model_name='goal',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed')], default='active', max_length=50),
        ),
    ]
