# Generated by Django 5.1.1 on 2024-09-19 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
        migrations.AddField(
            model_name='account',
            name='account_icon',
            field=models.CharField(default='default_icon', max_length=255),
        ),
        migrations.AddField(
            model_name='account',
            name='include_in_total',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='account',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('checking', 'Checking'), ('savings', 'Savings')], max_length=255),
        ),
    ]
