# Generated by Django 5.1.1 on 2024-09-20 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_account_color_account_account_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_number',
            field=models.CharField(default=1, max_length=26, unique=True),
            preserve_default=False,
        ),
    ]
