# Generated by Django 5.1.1 on 2024-10-17 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_account_account_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='currency',
        ),
    ]
