# Generated by Django 5.1.1 on 2024-10-18 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transfer',
            old_name='name',
            new_name='transfer_name',
        ),
    ]
