# Generated by Django 5.1.1 on 2024-09-19 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_category_category_icon_category_is_deleted_and_more'),
        ('transfers', '0002_alter_transfer_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.category'),
        ),
    ]
