# Generated by Django 5.1.1 on 2024-09-19 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0003_transfer_is_deleted_alter_transfer_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='transfer_date',
            field=models.DateTimeField(),
        ),
    ]
