# Generated by Django 5.1.1 on 2024-09-20 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_account_account_number'),
        ('transfers', '0004_alter_transfer_transfer_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='recipient_account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recipient_account', to='accounts.account'),
            preserve_default=False,
        ),
    ]
