# Generated by Django 5.1.1 on 2024-09-20 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_account_account_number'),
        ('transfers', '0005_transfer_recipient_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='recipient_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipient_account', to='accounts.account'),
        ),
    ]
